### ISSUE TITLE
Merlin won't show up on the web UI , probably due failed RabbitMQ connection

### ISSUE THREAD

**Issue by agentzex** [MythicAgents/merlin#10]
[*] Mythic Local Version:  v3.0.1-rc19

Installed merlin the usual way with sudo ./mythic-cli  install

After successful installation  (this is the docker version - ne0nd0g/merlin-base:v1.3.0) , seems like merlin docker is failing to connect to RabbitMQ. 

This could also be identified using the mythic-cli logs

```
osboxes@osboxes:~/Desktop/mythic/Mythic$ sudo ./mythic-cli  logs merlin
[*] To enable debug logging, set `MYTHIC_ENVIRONMENT` variable to `testing`
[*] Mythic PayloadType Version: 12
[*] PayloadType PyPi Version: 0.1.7
[*] Hostname specified as default 'hostname' value, thus will fetch and use the current hostname of the Docker container or computer

[*] Setting hostname (which should match payload type name exactly) to: merlin
[*] Trying to connect to rabbitmq at: 127.0.0.1:5672
[*] Trying to connect to rabbitmq at: 127.0.0.1:5672
[*] Trying to connect to rabbitmq at: 127.0.0.1:5672
[*] Trying to connect to rabbitmq at: 127.0.0.1:5672
[*] Trying to connect to rabbitmq at: 127.0.0.1:5672
[*] Trying to connect to rabbitmq at: 127.0.0.1:5672
```

And this goes on forever^

After doing some research it seems like although the correct rabbitmq user and password are set in the env variables inside the merlin docker,  'mythic_service.py' from mythic-payloadtype-container lib , is failing to connect to it.

From rabbitmq logs seems like the attempt is failed because the default 'mythic_password' is used in the connection attempt instead of the actual password in the env variable.

After setting the correct rabbitmq password in  'mythic_password' key in /Mythic/merlin/mythic/rabbitmq_config.json instead , I could  see that the connection  is successful in logs:
```
[+] Ready to go!
[*] mythic_service - Waiting for messages in mythic_service with version 12.
[*] mythic_service - total instances of merlin container running: 1

```
 but it still seems to not load merlin correctly in the web UI. 

This is as far as I got, as I'm new to the Mythic source code, but from a quick check, looks like other agents (like Medusa ) use the newer 'mythic_container' instead of 'mythic-payloadtype-container' lib, which handles the rabbitmq connection so it might be related to merlin still using the obsolete lib ? (https://github.com/MythicMeta/Mythic_PayloadType_Container/tree/master)

**Comment by Ne0nd0g** [comment]
@agentzex Merlin on Mythic doesn't currently work with Mythic v.3.0.0. I am in the middle of updating it. If you would like to try an incomplete version, use my `v.3.0.0` branch.

**Comment by agentzex** [comment]
Thanks for letting me know, will sure try v.3.0.0

Maybe it's worth adding some comment about the incompatibility in the readme file for the meantime until a new version is released though, for anyone who will face the same issues, since this version (merlin-base:v1.3.0) is still the default version that Mythic use 😊

**Comment by Ne0nd0g** [comment]
Just to follow up, Merlin on Mythic was updated to work with Mythic v3.0.0
