### ISSUE TITLE
Issue while executing commands with merlin shared library object on Linux system

### ISSUE THREAD

**Issue by timukas** [MythicAgents/merlin#12]
Hello,

Merlin shared payload for Linux X64 compiled with default settings in Mythic and uses http profile.

Payload .so loaded on Ubuntu 22.04 (x64) with following command:
`LD_PRELOAD=/tmp/merlin /usr/bin/whoami`

After that, new callback successfully received by Mythic.

Now starts the weird part.
Running shell commands "shell pwd" with Merlin .so payload do not show any output.
While running native commands "pwd", etc generates correct output.

![Screenshot_2023-08-04_16_12_56](https://github.com/MythicAgents/merlin/assets/1915618/dd603cc7-5f4f-4b5f-90d5-6d237b4e1eaf)

Any ideas/suggestions/hints on how to get output of "shell" commands?

p.s. we use latest versions of mythic, profiles and agents.

**Comment by Ne0nd0g** [comment]
Interesting! I'll take a look and see what I can figure out. Does the debug output from the agent provide any clues? Does the memfd or run command work?

**Comment by timukas** [comment]
Shell and run commands are not giving any answers back.
All native commands works find.

Below 3 debug files from 3 different callbacks from same merlin.so file.

I run native "pwd" command - got result back

"shell pwd" - did not get result

"run pwd" - also did not get the result back

[merlin_native_command_pwd.txt](https://github.com/MythicAgents/merlin/files/12262000/merlin_native_command_pwd.txt)
[merlin_shell_pwd.txt](https://github.com/MythicAgents/merlin/files/12262002/merlin_shell_pwd.txt)
[merlin_run_pwd.txt](https://github.com/MythicAgents/merlin/files/12262003/merlin_run_pwd.txt)

**Comment by Ne0nd0g** [comment]
The problems is that because the `LD_PRELOAD` environment variable is set, every time a new process is started, it copies the parent's environment variables causing `LD_PRELOAD` to fire again. You should be getting a new agent each time. A temporary work around is to run `env unset LD_PRELOAD` as the first command when the agent checks in
