### ISSUE TITLE
Cannot add HTTP headers

### ISSUE THREAD

**Issue by GeorgePatsias** [MythicAgents/merlin#15]
Hello,

I have an issue with the merlin payload on trying to load a profile and add more HTTP headers to it.
I tried a custom http header and the Host header.
The only thing that is able to change is the User-Agent only.

Regards,

**Comment by Ne0nd0g** [comment]
@GeorgePatsias I recently worked on this due to feedback from another user. Try using the https://github.com/MythicAgents/merlin/tree/http-headers branch and let me know if that works out for you.

**Comment by som3canadian** [comment]
Yep it worked on https://github.com/MythicAgents/merlin/tree/http-headers

**Comment by Ne0nd0g** [comment]
Perfect. I've merged those changes into the `dev` branch and plan to release them in the `main` branch soon.
