### ISSUE TITLE
Using garble for code obfuscation

### ISSUE THREAD

**Issue by boomaad** [MythicAgents/merlin#19]
Can add a new usage https://github.com/burrowers/garble Is there a function for project confusion

**Comment by boomaad** [comment]
Can reduce memory features in EDR

**Comment by Ne0nd0g** [comment]
@boomaad When building a Merlin agent through Mythic, there is a toggle to use Garble that reads: `Use Garble to obfuscate the output Go executable?`

![image](https://github.com/user-attachments/assets/896a3cb9-35d4-4f94-b3a4-3a5cc3c1f141)


If you're building Merlin outside of Mythic then you can use the `garble` targets in the Makefile (e.g., make windows-garble) https://github.com/Ne0nd0g/merlin-agent/blob/9014fbc04ca235b472d2ecc28f2f7d98af91aa64/Makefile#L105
