### ISSUE TITLE
restrictive license GNU General Public License v3.0

### ISSUE THREAD

**Issue by superuser5** [MythicAgents/merlin#2]
Hello,

Thank you for great implant.

Some companies forbid use applications with the "GNU General Public License v3.0" license.

I wonder if it is possible to change license to less restrictive licenses like the following:
- BSD 3-Clause License  (as other MythicAgents Nimplant or Apollo or venus)
- MIT License (modern version https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#Modern_Style_with_sublicense)
- Apache License Version 2.0, January 2004

many thanks in advance.

**Comment by Ne0nd0g** [comment]
Hey @superuser5 thanks for reaching out. Do you have any additional details on what about GPL licensing makes it an obstacle? Do you have a specific use case you could share? There are certain attributes about the license that I do want to stand by.

**Comment by superuser5** [comment]
Hey Ne0nd0g, I checked for more details and i cannot find why they are forbidden, just listing that licenses are prohibited from use. I will try reach out legal team if they could provide more details. Looking at the Github's overview of the license conditions and the following condition i think is an obstacle "Same license" from https://github.com/MythicAgents/merlin/blob/main/LICENSE

**Comment by Ne0nd0g** [comment]
I'm going to stick with the license I have for now.
