### ISSUE TITLE
Build error for freebsd

### ISSUE THREAD

**Issue by timukas** [MythicAgents/merlin#21]
Hi,

Latest Mythic with latest merlin agent fires an error when building default payload for freebsd:

```
Status	 Error
Step Output	# github.com/Ne0nd0g/merlin-agent/v2/commands
/go/pkg/mod/github.com/!ne0nd0g/merlin-agent/v2@v2.4.1/commands/shell_freebsd.go:36:12: undefined: fmt
Step Error	exit status 1
```

Any hints/ideas how to fix it?

**Comment by Ne0nd0g** [comment]
Is this the same issue as https://github.com/MythicAgents/merlin/issues/17 ?

**Comment by timukas** [comment]
Yes, looks like same.

**Comment by Ne0nd0g** [comment]
Closing because it is a duplicate of #17
