### ISSUE TITLE
Merlin payload generation failing due to Go version incompatibility between code and build container

### ISSUE THREAD

**Issue by stephenbradshaw** [MythicAgents/merlin#23]
When trying to build a Merlin payload on Mythic `v3.3.1-rc28` and Merlin Mythic Agent commit [ef3a846](https://github.com/MythicAgents/merlin/commit/ef3a846c5bcbfcc4872737cc08c5ab80d278df8f), the following error is experienced.

```
go list error: exit status 1:
[SNIP]
go: go.mod requires go >= 1.22.0 (running go 1.21.13; GOTOOLCHAIN=local)
```

Looks like this is a conflict between the Go version 1.21.13 in container `docker.io/ne0nd0g/merlin-mythic:v1.0.2` as specified [here](https://github.com/MythicAgents/merlin/blob/main/config.json#L9) and the Go version 1.22.0 required for compilation [here](https://github.com/MythicAgents/merlin/blob/main/Payload_Type/merlin/agent/go.mod#L3).

**Comment by django-88** [comment]
I am having the same issue. Tried many things none of them working. Anybody had success?

**Comment by django-88** [comment]
@stephenbradshaw @Ne0nd0g 
i did a quick workaround for the problem

Enter the container of merlin:
docker exec -it <container_id_or_name> /bin/bash

remove existing go version:

sudo rm -rf /usr/local/go

download latest:

wget https://go.dev/dl/go<VERSION>.linux-amd64.tar.gz

extract and install:

sudo tar -C /usr/local -xzf go<VERSION>.linux-amd64.tar.gz

update Path:

echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc

source ~/.bashrc

For me this worked!

**Comment by Ne0nd0g** [comment]
@stephenbradshaw & @django-88 thanks for reporting  this and finding a workaround. I'm looking into this now.

**Comment by Ne0nd0g** [comment]
@stephenbradshaw Everything should be fixed now, just needed to change one line in the config file to pull the correct image. Can you try to install Merlin from source again to see if you have any errors? 

https://github.com/MythicAgents/merlin/blob/43e64c5567540d7c9aa2065377acc8a887ef6278/config.json#L9

**Comment by stephenbradshaw** [comment]
Builds now, fixed, thanks 👍
