### ISSUE TITLE
An error is reported when generating the openbsd arm payload

### ISSUE THREAD

**Issue by SeeNanshaneisurely** [MythicAgents/merlin#7]
hello!
Using the mythical merlin module,An error is reported when generating the openbsd arm payload,How to solve
![1](https://user-images.githubusercontent.com/57738442/222029326-8ee9d55e-456e-440b-8c3b-6427de696e16.png)

**Comment by Ne0nd0g** [comment]
@SeeNanshaneisurely thanks for reporting the issue. I've pushed an update that resolves this error. Reinstall the Merlin agent to ensure it uses v1.5.1 and you should be good to go. Please let me know if there are any other issues.

**Comment by SeeNanshaneisurely** [comment]
@Ne0nd0g Thanks for your quick response, the previous issue has been resolved. But encountered a new problem:
After the openbsd arm payload is generated, an error is reported, and the error result is shown in the figure:
![3](https://user-images.githubusercontent.com/57738442/222356062-3748870b-7142-43d8-9b0a-dab9dc30cf1f.png)

**Comment by Ne0nd0g** [comment]
What OpenBSD architecture are you using? The `arm` setting is for 32-bit, we need `arm64` for 64-bit. As a temporary work around until I push an update, you can add `arm64` to this list: https://github.com/MythicAgents/merlin/blob/02f7c90e2a9e8ee022e451a33a960e8c7d484b91/Payload_Type/merlin/mythic/agent_functions/builder.py#L46  restart Mythic, and then create a new payload.

**Comment by SeeNanshaneisurely** [comment]
Thanks, it has been resolved. This system is arm64 bit
