### ISSUE TITLE
merlin multi-platform testing

### ISSUE THREAD

**Issue by SeeNanshaneisurely** [MythicAgents/merlin#9]
Hello! 
When testing merlin on an IoT (Android) device, the generated arm32/64 shell fails to execute. Is there any solution?
![image](https://user-images.githubusercontent.com/57738442/229678637-cca7351b-aed4-4809-8401-814470128d8d.png)

**Comment by Ne0nd0g** [comment]
Do you know the full file path to the shell on this IoT device? The `shell` command is essentially the same as using the `run` command and passing the shell file path as the first argument. The best workaround is to use the `run` command.

**Comment by SeeNanshaneisurely** [comment]
Hello!
The binary file is executed successfully, and there is a request from the network to C2IP, but C2 cannot receive the shell
![image](https://user-images.githubusercontent.com/57738442/230329707-47b95463-8dd0-40c0-a58c-9ade87049e55.png)

**Comment by Ne0nd0g** [comment]
I'm not certain what you are saying. You executed the Agent, but the connection to the Merlin server isn't successful? You would need to troubleshoot the network connection. You can do a `tcpdump` where the Merlin Server is listening to see if packets are making its way there. When you setup the Merlin Server, ensure you set the listener's interface to `0.0.0.0` so that it can receive connections on all ports.

**Comment by SeeNanshaneisurely** [comment]
Hello!
 I have an Android device running an agent that shows it is connecting to my Merlin server when I execute 'netstat -an' on the device. However, my Merlin server is not receiving callbacks from the Android device. 
 The environment is as follows: I can successfully ping my Merlin server from my Android device using 'ping -c 2', and I can connect to the Android device using 'adb' on the Merlin server. Now I'm not sure what issues might be preventing my Merlin server from receiving callbacks.The Merlin server firewall is closed, and the port is also opened at 0.0.0.0.

**Comment by SeeNanshaneisurely** [comment]
happiness!
Thanks a lot for your answer. Problem solved, Merlin server CPU is too low.
